### ISSUE TITLE
自动化测试分组删除存在严重BUG

### ISSUE THREAD

**Issue by applexph** [eolinker/eoLinker-API-Management-3.5.1-for-PHP#10]
自动化测试中如果删除某个分组  将会导致整个项目的所有自动化测试接口被删除。
AutomatedTestCaseGroupDao > deleteGroup方法中  修复方案将project_id 替换为 group_id
`$db->prepareExecuteAll('DELETE FROM eo_project_test_case_single WHERE eo_project_test_case_single.caseID IN (SELECT eo_project_test_case.caseID FROM eo_project_test_case WHERE eo_project_test_case.groupID = ?);', array(
                $group_id
            ));`

**Comment by applexph** [comment]
自动化测试存在功能缺陷。  自动化测试中  raw参数  不能和 form参数同时使用。

**Comment by eolinker** [comment]
您好，目前自动化测试删除的问题已经修复。
