### ISSUE TITLE
JSON嵌套数组不能解析和生成

### ISSUE THREAD

**Issue by jangjoe** [eolinker/eoLinker-API-Management-3.5.1-for-PHP#11]
**首先非常感谢能有这样优秀的中文产品可以开源使用**，这在很大程度上帮助我很好的管理文档内容。在进行添加接口我遇到了嵌套数组的问题。
我的业务需求特性要求我需要传递一个二维数组，其中的内容不定长度但要求有先后顺序。因此我定义了如下的JSON数据形式：
```json
{
  "Arrs": [
    [{
      "Value": "GroupA_ValueA",
      "Name": "GroupA_NameA"
    }, {
      "Value": "GroupA_ValueB",
      "Name": "GroupA_NameB"
    }],
    [{
      "Value": "GroupB_ValueA",
      "Name": "GroupB_NameA"
    }, {
      "Value": "GroupB_ValueB",
      "Name": "GroupB_NameB"
    }]
  ]
}
```
在我的理解里它应该转换为
* Arrs (Array)
  * 0 (Array)
    * 0 (Object)
      * Value (String)
      * Name (String)
    * 1 (Object)
      * Value (String)
      * Name (String)
  * 1 (Array)
    * 0 (Object)
      * Value (String)
      * Name (String)
    * 1 (Object)
      * Value (String)
      * Name (String)

然而我将这段JSON导入后，得到的却是如下结构：
* Arrs (Array)
  * Value (String)
  * Name (String)

最后生成的JSON变为了如下的一维数组：
```JSON
{
    "Arrs":[
        {
            "Value":"df#oF)",
            "Name":")qv4%t"
        }
    ]
}
```

与我的数据输入有明显差别，不知道遇到这种情况的时候有没有对应的解决方案，迫切需要你们的帮助，非常感谢。

**Comment by ljgade** [comment]
感谢您的反馈，我们会尽快修复这个问题

**Comment by eolinker** [comment]
您好，新的版本中已经修复该问题，感谢您的意见。
如果有使用上的问题，欢迎加入我们的用户讨论群，里面会有专人客服为您解答。
