### ISSUE TITLE
能否提供docker镜像

### ISSUE THREAD

**Issue by rmfish** [eolinker/eoLinker-API-Management-3.5.1-for-PHP#15]
用docker部署更简便，版本管理也方便一些

**Comment by qq1324185** [comment]
https://hub.docker.com/r/eolinker/eolinker-api-management-system/
您好，您可参考该网站教程对eolinker开源版进行部署

**Comment by ah-kevin** [comment]
部署的时候 mysql的data 好想只能-v 单独映射一个.不能同步之前的data

**Comment by qq1324185** [comment]
目前开源版3.5.0镜像可支持映射数据卷，具体可参考
https://hub.docker.com/r/eolinker/eolinker-api-management-system/
若想将之前的数据同步，您需要将先前数据库拉入映射后的目录中，修改数据库的文件夹拥有者即可
