### ISSUE TITLE
点击进入安装指南链接报“403”错误

### ISSUE THREAD

**Issue by wesleyang2018** [eolinker/eoLinker-API-Management-3.5.1-for-PHP#18]
1.是否需要购买后才会给用户名，密码进入安装指南页面？
2.若无需购买，有没有其他安装指南链接？
3.QQ群点击后无法加入？

**Comment by Charleslingchaos** [comment]
1、官网的开源版安装指南貌似在维护，可以去W3Cschool那里：https://www.w3cschool.cn/eolinker/eolinker-jrid2hnf.html
2、Q群之前好像是已经满了，有个新群：707530721
