### ISSUE TITLE
项目文档希望能加入图片上传功能

### ISSUE THREAD

**Issue by carpcai** [eolinker/eoLinker-API-Management-3.5.1-for-PHP#19]
项目文档希望能加入图片上传功能，每次想添加图片都挺麻烦的

**Comment by feidy** [comment]
同上
我在看3.19的代码时，发现有图片上传plugins，不知道为何后面版本去掉了。
这个功能是不是在开源版本中不提供？

**Comment by feidy** [comment]
也有可能是七牛的原因，开源版本关闭了图片上传功能。
其实也可以打开，开发者可以根据情况实现七牛或者本地存储。
