### ISSUE TITLE
添加全局变量作用域到参数值的功能

### ISSUE THREAD

**Issue by liutf** [eolinker/eoLinker-API-Management-3.5.1-for-PHP#5]
![环境管理设置](https://note.youdao.com/yws/public/resource/1c8b8602d42c2dc4aeb2fe9258606029/xmlnote/4A2716F26C9247909040ECD804EDF742/2608)

![接口测试](https://note.youdao.com/yws/public/resource/1c8b8602d42c2dc4aeb2fe9258606029/xmlnote/00B73CCA5E9E4229850DFF93828D7967/2617)

 如上图，我添加了个uname的全局变量，我希望在接口测试的请求参数中，key: uname，能通过语法"{{uname}}"解析到我在全局变量中设置的值“zhangsan”.

Postman有此功能，希望eolinker也能跟进上，更好用。
![Poastman](https://note.youdao.com/yws/public/resource/1c8b8602d42c2dc4aeb2fe9258606029/xmlnote/67A049367B8E413794340B7FEA629D4A/2615)

   翘首以待。谢谢！

**Comment by eolinker** [comment]
感谢您的意见，我们将尽快实现该功能，感谢
