### ISSUE TITLE
自动化测试和API接口测试不一致

### ISSUE THREAD

**Issue by dengly** [eolinker/eoLinker-API-Management-3.5.1-for-PHP#6]
版本：
3.1.9

问题：
在API接口测试时，form和RESTful的参数可以选择以json方式发生。但是在自动化测试时选择API接口，form和RESTful的参数都不能以json方式发生。

希望这个自动化测试的form和RESTful的参数也可以以json方式发生。

**Comment by eolinker** [comment]
您好，新的版本中已经修复该问题，感谢您的意见
